# Generated by Django 2.2.5 on 2020-02-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200228_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guests',
            field=models.IntegerField(default=0),
        ),
    ]
